title:
  start:
    px: 223
    py: 252
  fgHexColor: "#000000"
  fontSize: 72
  fontStyle: Bold
  maxWidth: 946
  lineSpacing: 10
category:
  start:
    px: 223
    py: 211
  fgHexColor: "#E5B52A"
  fontSize: 42
  fontStyle: Regular
info: # disabled
  start:
    px: 223
    py: 120
  fgHexColor: "#FFFFFF" 
  fontSize: 1
  fontStyle: Regular
  separator: " - "
tags: # disabled
  start:
    px: 223
    py: 475
  fgHexColor: "#FFFFFF"
  bgHexColor: "#FFFFFF"
  fontSize: 1
  fontStyle: Medium
  boxAlign: Left
  boxSpacing: 6
  boxPadding:
    top: 6
    right: 10
    bottom: 6
    left: 8